In [1]:
import pandas as pd

df_exams = pd.read_csv(r"D:\python-for-data-science-main\02.Intro to Pandas\StudentsPerformance.csv")
df_exams.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [2]:
df_exams['math score'].count()

1000

In [3]:
df_exams['math score'].sum()

66089

In [4]:
df_exams['math score'].mean()

66.089

In [5]:
df_exams['math score'].std()

15.163080096009468

In [6]:
df_exams['math score'].max()

100

In [7]:
df_exams['math score'].min()

0

In [8]:
df_exams.describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [9]:
df_exams ['math score'] + df_exams ['reading score'] + df_exams ['writing score']

0      218
1      247
2      278
3      148
4      229
      ...
995    282
996    172
997    195
998    223
999    249
Length: 1000, dtype: int64

In [10]:
df_exams['average'] = df_exams ['math score'] + df_exams ['reading score'] + df_exams ['writing score'] / 3
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,average
0,female,group B,bachelor's degree,standard,none,72,72,74,168.666667
1,female,group C,some college,standard,completed,69,90,88,188.333333
2,female,group B,master's degree,standard,none,90,95,93,216.000000
3,male,group A,associate's degree,free/reduced,none,47,57,44,118.666667
4,male,group C,some college,standard,none,76,78,75,179.000000
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,218.666667
996,male,group C,high school,free/reduced,none,62,55,55,135.333333
997,female,group C,high school,free/reduced,completed,59,71,65,151.666667
998,female,group D,some college,standard,completed,68,78,77,171.666667
999,female,group D,some college,free/reduced,none,77,86,86,191.666667

In [11]:
df_exams.round(2)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,average
0,female,group B,bachelor's degree,standard,none,72,72,74,168.67
1,female,group C,some college,standard,completed,69,90,88,188.33
2,female,group B,master's degree,standard,none,90,95,93,216.00
3,male,group A,associate's degree,free/reduced,none,47,57,44,118.67
4,male,group C,some college,standard,none,76,78,75,179.00
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,218.67
996,male,group C,high school,free/reduced,none,62,55,55,135.33
997,female,group C,high school,free/reduced,completed,59,71,65,151.67
998,female,group D,some college,standard,completed,68,78,77,171.67
999,female,group D,some college,free/reduced,none,77,86,86,191.67